name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag docker-compose-aarch64-builder
      - name: Generate a docker-compose-Linux-aarch64
        run: |
          mkdir -p ./dist
          docker run --rm -v "$(pwd)/dist":/dist docker-compose-aarch64-builder
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: docker-compose-Linux-aarch64
          path: ./dist
